# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/loss.faster_rcnn_loss.ipynb.

# %% auto 0
__all__ = ['FasterRCNNLoss']

# %% ../../nbs/loss.faster_rcnn_loss.ipynb 2
from fastai.vision.all import *
from .roi_loss import ROILoss
from .rpn_loss import RPNLoss

# %% ../../nbs/loss.faster_rcnn_loss.ipynb 3
class FasterRCNNLoss(Module):
    def __init__(self):
        self.rpn_loss_func= RPNLoss()
        self.roi_loss_func= ROILoss()
        self.rpn_attrs= ['rpn_loss','rpn_cls_loss','rpn_reg_loss']
        self.roi_attrs= ['roi_loss','roi_cls_loss','roi_reg_loss']
        
    def set_metrics_attr(self, attr_list, losses):
        [setattr(self, name, value) for name, value in zip(attr_list, losses)]
        
    def forward(self, y_pred, rpn_gt, roi_gt, yb):
        rpn_reg_feats, rpn_cls_feats, rois= y_pred[:3]
        roi_reg_feats, roi_cls_feats=y_pred[3:]
        rpn_losses= self.rpn_loss_func(rpn_reg_feats,rpn_cls_feats,rpn_gt)
        roi_losses= self.roi_loss_func(roi_reg_feats,roi_cls_feats,roi_gt)
        self.set_metrics_attr(self.rpn_attrs, rpn_losses)
        self.set_metrics_attr(self.roi_attrs, roi_losses)
        loss =self.rpn_loss+self.roi_loss
        return loss

