# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/loss.loss.ipynb.

# %% auto 0
__all__ = ['FasterRCNNLoss']

# %% ../../nbs/loss.loss.ipynb 2
from fastai.vision.all import *
from .roi_loss import ROILoss
from .rpn_loss import RPNLoss

# %% ../../nbs/loss.loss.ipynb 3
class FasterRCNNLoss(Module):
    def __init__(self):
        self.rpn_loss_func= RPNLoss
        self.roi_loss_func= ROILoss
        self.rpn_loss= 0
        self.roi_loss= 0
        self.rpn_cls_loss= 0
        self.rpn_cls_loss= 0
        self.roi_reg_loss= 0
        self.roi_reg_loss= 0
    
    def forward(self, y_pred, rpn_gt, roi_gt):
        gt_rpn_cls, gt_rpn_reg, pos_ind= rpn_gt
        gt_roi_cls, gt_roi_reg= roi_gt
        rpn_reg_feats, rpn_cls_feats, roi_reg_feats, roi_cls_feats, rois=list(y_pred.values())
        self.rpn_loss, self.rpn_cls_loss, self.rpn_reg_loss=  self.rpn_loss_func(rpn_reg_feats, 
                                                                                rpn_cls_feats, 
                                                                                gt_rpn_cls, 
                                                                                gt_rpn_reg, 
                                                                                pos_ind)
        
        self.roi_loss, self.roi_cls_loss, self.roi_reg_loss= self.roi_loss_func(roi_reg_feats,  
                                                                               roi_cls_feats,  
                                                                               gt_roi_reg,  
                                                                               gt_roi_cls)
        return (self.rpn_loss+self.roi_loss).sum()
