# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/loss.roi_loss.ipynb.

# %% auto 0
__all__ = ['ROILoss']

# %% ../../nbs/loss.roi_loss.ipynb 2
from fastai.vision.all import *
from .base import BaseLoss

# %% ../../nbs/loss.roi_loss.ipynb 3
class ROILoss(BaseLoss):
    def __init__(self):
        self.roi_sigma=1.
        super().__init__()
    
    def forward(self, 
                 roi_reg_feats, 
                 roi_cls_feats, 
                 roi_gt):
        gt_roi_cls, gt_roi_reg= roi_gt
        roi_cls_loss= self.cls_loss_func(roi_cls_feats, gt_roi_cls)
        roi_reg_loss= self.reg_loss_func(roi_reg_feats, 
                                             gt_roi_reg, 
                                             gt_roi_cls, 
                                             self.roi_sigma)
        roi_loss= self.joint_loss(roi_reg_loss, roi_cls_loss)
        return [roi_loss, roi_cls_loss, roi_reg_loss]
