# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/loss.rpn_loss.ipynb.

# %% auto 0
__all__ = ['RPNLoss']

# %% ../../nbs/loss.rpn_loss.ipynb 2
from fastai.vision.all import *
from .base import BaseLoss

# %% ../../nbs/loss.rpn_loss.ipynb 3
class RPNLoss(BaseLoss):
    def __init__(self, 
                 rpn_sigma=3.):
        self.rpn_sigma= 3.
        super().__init__()
    
    def forward(self, 
                 rpn_reg_feats, 
                 rpn_cls_feats,
                 rpn_gt):
        gt_rpn_cls, gt_rpn_reg= rpn_gt
        rpn_cls_loss= self.cls_loss_func(rpn_cls_feats, gt_rpn_cls)
        rpn_reg_loss= self.reg_loss_func(rpn_reg_feats, 
                                             gt_rpn_reg, 
                                             gt_rpn_cls, 
                                             self.rpn_sigma)
        rpn_loss= self.joint_loss(rpn_reg_loss, rpn_cls_loss)
        return [rpn_loss, rpn_cls_loss, rpn_reg_loss]
